import { oxlint } from '@debbl/oxc-config'
import { defineConfig } from 'oxlint'

export default defineConfig({
  extends: [oxlint({ react: true, a11y: true })],
  ignorePatterns: [
    // Next.js rewrites this on every build.
    '**/next-env.d.ts',
    // Generated by fumadocs-mdx on every dev and build.
    '**/.source/**',
  ],
  overrides: [
    {
      // The Next.js rules only mean anything where Next actually runs. Left
      // global, `next/no-head-element` flags the plain `<head>` that a Vite or
      // TanStack Start root is supposed to render.
      files: ['apps/website/**', 'playground/nextjs/**'],
      plugins: ['nextjs'],
      rules: {
        // A Next.js route module is *required* to export generateMetadata,
        // generateStaticParams and dynamicParams beside its component. Fast
        // refresh is not the constraint here; the framework's contract is.
        'react/only-export-components': 'off',
      },
    },
    {
      files: ['**/test/**'],
      rules: {
        // Tests read a hook's return value by assigning it to an outer
        // variable from a probe component. That is the point of the probe.
        'react/globals': 'off',
      },
    },
  ],
})
